Repository Arggusx/onlineMenu, pull requests merged in 2025-02, with the labels that each got.

#2 New additions
  src/components/Main.tsx
Labels: documentation

#3 Melhoria de código, adição de base de dados e adição e arquivos
  src/App.tsx
  src/Menu.tsx
  src/components/Header.tsx
  src/components/Main.tsx
  src/components/MenuItem.tsx
  src/itensData.tsx
Labels: enhancement

#5 Adiciona a nova opção de bebidas: Água com Gás e água mineral (Sem Gás).
  src/Menu.tsx
  src/itensData.tsx
Labels: enhancement

#6 Adiciona novo elemento e corrige o scroll
  src/Menu.tsx
  src/components/Main.tsx
  src/components/Nav.tsx
  src/itensData.tsx
Labels: enhancement

#7 meta/build: Correções e limpezas no package-lock e README.
  README.md
  package-lock-DESKTOP-Douglas.json
  package-lock.json
Labels: documentation, enhancement
